name: Code Quality Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run Ruff
        run: |
          ruff check .

      - name: Run isort
        run: |
          isort . --check-only
